[package]
name = "cybervision"
version = "0.13.0"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/cybervision"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
image = { version = "0.24.5", features = ["png", "jpeg", "tiff"] }
indicatif = "0.17.3"
tiff = "*"
rayon = "*"

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
