[package]
name = "cybervision"
version = "0.13.0"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/cybervision"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", default_features = false, features = ["std", "derive", "help", "usage", "suggestions"] }
image = { version = "0.24.5", default_features = false, features = ["png", "jpeg", "tiff", "jpeg_rayon"] }
indicatif = { version = "0.17.3", default_features = false }
tiff = "*"
rayon = "*"
rand = { version = "0.8.5", default_features = false, features = ["std", "std_rng", "small_rng"] }
ndarray = { version = "*", default_features = false, features = ["std"] }
ndarray-linalg = { version = "0.16.0", default_features = false }

[features]
default = []
gpu = []

[target.'cfg(target_os = "macos")'.dependencies]
lapack-src = { version = "0.8", default_features = false, features= ["accelerate"] }

[target.'cfg(any(target_os = "linux", target_os = "windows"))'.dependencies]
lapack-src = { version = "0.8", default_features = false, features= ["netlib"] }
netlib-src = { version = "*", default_features = false, features = ["cblas", "static"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
