[package]
name = "cybervision"
version = "0.13.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
image = { version = "0.24.5", features = ["png", "jpeg", "tiff"] }
tiff = "0.9.0"

[profile.release]
strip = true
lto = true
