[package]
name = "cybervision"
version = "0.17.0"
edition = "2021"
authors = ["Dmitry Zolotukhin <zlogic@gmail.com>"]
repository = "https://github.com/zlogic/cybervision"
license = "Apache-2.0"
rust-version = "1.70"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3", default_features = false, features = ["std", "derive", "help", "usage", "suggestions"] }
image = { version = "0.24", default_features = false, features = ["png", "jpeg", "tiff", "jpeg_rayon"] }
indicatif = { version = "0.17", default_features = false }
tiff = "*"
rayon = "*"
rand = { version = "0.8", default_features = false, features = ["std", "std_rng", "small_rng"] }
nalgebra = { version = "0.32", features = ["rayon"] }
spade = { version = "2.2", default_features = false }
wgpu = { version = "0.17", default-features = false, features = ["wgsl"] }
pollster = { version = "0.3", default-features = false }
bytemuck = { version = "*", features = ["derive"] }
roots = { version = "0.0.8", default-features = false }

[profile.release]
strip = true
lto = true
codegen-units = 1
panic = "abort"
