# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, python_gpu ]
  pull_request:
    branches: [ master ]

jobs:
  validate:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      shell: sh
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install flake8 wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

  build:
    needs: validate
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-latest
          archs: x86_64 aarch64
          before_build: .github/dependencies/install-vulkan-linux.sh
          vulkan_sdk: /usr
        - os: macos-latest
          archs: x86_64 arm64
          prepare_vulkan_sdk: . .github/dependencies/build-vulkan-macos.sh
          vulkan_sdk: vulkan-sdk
        - os: windows-latest
          archs: AMD64
          prepare_vulkan_sdk: . .github/dependencies/build-vulkan-windows.sh
          vulkan_sdk: vulkan-sdk

    steps:
    - uses: actions/checkout@v3
    - name: Install cibuildwheel
      run: python3 -m pip install cibuildwheel==2.4.0
    - name: Install qemu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update -y
        sudo apt-get install qemu-user-static
    - name: Cache Vulkan SDK
      if: matrix.os != 'ubuntu-latest'
      id: cache-vulkan-sdk
      uses: actions/cache@v3
      with:
        path: vulkan-sdk
        key: ${{ matrix.os }}-${{ hashFiles('.github/dependencies/build-vulkan-*.sh') }}-vulkan-sdk
    - name: Prepare Vulkan SDK
      if: matrix.os != 'ubuntu-latest' && steps.cache-vulkan-sdk.outputs.cache-hit != 'true'
      shell: sh
      run: ${{ matrix.prepare_vulkan_sdk }}
    - name: Build wheels
      env:
        CIBW_BUILD_VERBOSITY: 1
        CIBW_ARCHS: ${{ matrix.archs }}
        CIBW_BEFORE_BUILD: ${{ matrix.before_build }}
        CIBW_ENVIRONMENT: VULKAN_SDK=${{ matrix.vulkan_sdk }}
        CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
          DYLD_LIBRARY_PATH=vulkan-sdk/lib delocate-listdeps {wheel} &&
          DYLD_LIBRARY_PATH=vulkan-sdk/lib delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
      run: python3 -m cibuildwheel --output-dir wheelhouse
    - name: Upload wheel artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cybervision-${{ matrix.os }}
        path: ./wheelhouse/*.whl
